name: dart_libp2p_pubsub
description: A comprehensive libp2p pubsub implementation for Dart, featuring GossipSub v1.1, FloodSub, and RandomSub protocols with message validation, peer scoring, and tracing support.
version: 1.2.1
repository: https://github.com/stephanfeb/dart_libp2p_pubsub
homepage: https://github.com/stephanfeb/dart_libp2p_pubsub
documentation: https://github.com/stephanfeb/dart_libp2p_pubsub/tree/main/docs
issue_tracker: https://github.com/stephanfeb/dart_libp2p_pubsub/issues

environment:
  sdk: ^3.5.0

dependencies:
  dart_libp2p: ^1.0.0
  dart_libp2p_kad_dht: ^1.2.0
  dcid: ^1.0.0

  collection: ^1.17.1
  logging: ^1.2.0
  protobuf: ^3.1.0
  x25519: ^0.1.1
  fixnum: ^1.1.0
  cryptography: ^2.7.0
  bs58: ^1.0.2
  dart_multihash: ^1.0.1
  base32: ^2.1.3
  uuid: ^4.4.2 
  synchronized: ^3.3.0+3
  dart_udx: ^2.0.1
  clock: ^1.1.2

dev_dependencies:
  mockito: ^5.4.4
  analyzer: ^6.0.0  
  build_runner: ^2.4.13
  protoc_builder: ^0.4.1
  test: ^1.24.0
  protoc_plugin: ^21.0.0
  lints: ^2.1.0
  fake_async: ^1.3.3 

targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - lib/src/pb/** # Your .proto directory
